apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: clusters.platform.knab-internal.com
spec:
  group: platform.knab-internal.com
  names:
    kind: Cluster
    plural: clusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              namespace:
                type: string
              region:
                type: string
              subnets:
                type: array