apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: queue
spec:
  forProvider:
    name: {{ $.observed.composite.resource.metadata.name }}
    region: eu-west-1