apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bravo
spec:
  destination:
    namespace: bravo
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/nzorn-knab/bravo
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
