apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: standardqueues.platform.knab-internal.com
spec:
  group: platform.knab-internal.com
  names:
    kind: StandardQueue
    plural: standardqueues
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string